apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapitest-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapitest
    spec:
      containers:
      - name: webapitest
        image: sh360.azurecr.io/webapitest:v4
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapitest-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: webapitest